export const ROUTE_PATHS = {
	HOME: '/',
	LOGIN: '/login',
	REGISTER: '/register',
	FORGOT_PASSWORD: '/forgot-password',
	RESET_PASSWORD: '/reset-password',
	VERIFY_EMAIL: '/verify-email',
	PROFILE: '/profile',
	CHAT: '/chat',
	CHAT_WITH_USER: '/chat/:userId',
	CHAT_WITH_USER_ID: '/chat/:userId/:chatId',
	SHOP: '/shop',
	CART: '/cart',
	DASHBOARD: '/dashboard',
}